"""The paper's tables, as LaTeX ``tabular`` bodies (each is ``\\input`` inside a table float).

Conventions (App. Statistical Analysis): the base model is a single evaluation; a fine-tuned cell is the mean
over training seeds with a 95% Student-t interval; a stereotype-minus-neutral difference has a
95% Welch-t interval (shaded column). Proportions print as ``.xxx``.
"""

from __future__ import annotations

import math
import statistics

import numpy as np

from bias_em.config import AXES, Model
from bias_em.directions import direction_file
from bias_em.stats import t_ci, welch_ci
from data import BROAD, CAPABILITY, FAMILIES, SEEDS, base, evaluation, values

GENERATED = "% Generated by paper/build.py from results/metrics.csv; do not edit by hand."
ARROW = {"Betley": r"$\downarrow$", "HarmBench": r"$\downarrow$", "StrongREJECT": r"$\downarrow$",
         "TruthfulQA": r"$\uparrow$", "MMLU-Pro": r"$\uparrow$", "HellaSwag": r"$\uparrow$",
         "IFEval": r"$\uparrow$", "Expression": ""}
SHADED = r">{\columncolor{c1worse}[\tabcolsep][0pt]}c"
FAMILY_ORDER = ["llama8b", "gemma12b", "apertus8b"]


# ---- number formats -------------------------------------------------------------------------

def f3(x: float, sign: bool = False) -> str:
    """Three decimals without the leading zero: '.050', '-.065'; '+.420' with ``sign``."""
    return ("-" if x < 0 else "+" if sign else "") + f"{abs(x):.3f}".removeprefix("0")


def ci(lo: float, hi: float) -> str:
    """'~$[.044{,}.057]$'; a negative bound prints as '{-}.005'."""
    def bound(x):
        s = f3(x)
        return "{-}" + s[1:] if s.startswith("-") else s
    return f"~$[{bound(lo)}{{,}}{bound(hi)}]$"


def cell(xs: list[float]) -> str:
    """A fine-tuned cell; a single seed prints without an interval."""
    if len(xs) == 1:
        return f"${f3(xs[0])}$"
    m, lo, hi = t_ci(xs)
    return f"${f3(m)}$" + ci(lo, hi)


def delta(neutral: list[float], stereo: list[float], bold: bool = True) -> str:
    d, lo, hi = welch_ci(neutral, stereo)
    s = f3(d, sign=True)
    return (rf"$\mathbf{{{s}}}$" if bold else f"${s}$") + ci(lo, hi)


# ---- Table 1 and its replications (§4.1, App. Other Model Families, App. Longer Training) ---------------

def table1() -> str:
    """Qwen2.5-7B-Instruct, five seeds; gender and race panels stacked."""
    def num(x):   # Table 1 prints a value that rounds to zero unsigned
        return ".000" if float(f"{x:.3f}") == 0 else f3(x)

    def interval(lo, hi):   # and its lower bound with a plain minus
        h = num(hi)
        return f"~$[{num(lo)}{{,}}{'{-}' + h[1:] if h.startswith('-') else h}]$"

    def mean_cell(xs):
        m, lo, hi = t_ci(xs)
        return f"${num(m)}$" + interval(lo, hi)

    lines = [GENERATED,
             r"\begin{tabular}{@{}c@{\hspace{4pt}}l c c @{\hspace{8pt}} c c " + SHADED + "@{}}",
             r"\toprule"]
    for i, axis in enumerate(AXES):
        a = axis[0]
        if i:
            lines.append(r"\midrule")
        lines += [rf"\multicolumn{{7}}{{c}}{{\textit{{{axis.capitalize()}}}}} \\", r"\cmidrule{1-7}",
                  r" & \textbf{Evaluation} & $\mathcal{M}_{\text{base}}$ & $\mathcal{M}_{\text{benign}}$ & "
                  rf"$\mathcal{{M}}^{{\mathrm{{{a}}}}}_{{\text{{neutral}}}}$ & $\mathcal{{M}}^{{\mathrm{{{a}}}}}_{{\text{{stereo}}}}$ & "
                  rf"$\boldsymbol{{\Delta}}^{{\mathrm{{{a}}}}}$ \\", r"\cmidrule{1-7}"]
        for block, (rows, label) in enumerate(((BROAD, r"\shortstack{Broad\\misalign.}"), (CAPABILITY, "Capab."))):
            if block:
                lines.append(r"\cmidrule{1-7}")
            for j, m in enumerate(rows):
                ben, neu, ste = (evaluation("qwen7b", c, m) for c in ("benign", f"{axis}-neutral", f"{axis}-stereotype"))
                d, lo, hi = welch_ci(neu, ste)
                lead = rf"\multirow{{{len(rows)}}}{{*}}{{\rotatebox[origin=c]{{90}}{{{label}}}}}" if j == 0 else ""
                lines.append(f"{lead} & {m} {ARROW[m]} & ${num(base('qwen7b', m))}$ & {mean_cell(ben)} & "
                             f"{mean_cell(neu)} & {mean_cell(ste)} & "
                             rf"$\mathbf{{{'+' if d > 0 else ''}{num(d)}}}$" + interval(lo, hi) + r" \\")
    return "\n".join(lines + [r"\bottomrule", r"\end{tabular}"]) + "\n"


def table1_families() -> str:
    """Table 1 on Llama-3.1-8B, Gemma-3-12B and Apertus-8B, three seeds."""
    header = " & ".join([r"\textbf{Evaluation}", r"$\mathcal{M}_{\text{base}}$"] + [
        rf"$\mathcal{{M}}^{{\mathrm{{{a[0]}}}}}_{{\text{{{v}}}}}$" if v else rf"$\boldsymbol{{\Delta}}^{{\mathrm{{{a[0]}}}}}$"
        for a in AXES for v in ("neutral", "stereo", None)])
    lines = [GENERATED, r"\small",
             r"\begin{tabular}{@{}l c @{\hspace{6pt}} c c " + SHADED + r" @{\hspace{6pt}} c c " + SHADED + "@{}}",
             r"\toprule", header + r" \\"]
    for model in FAMILY_ORDER:
        lines += [r"\midrule", rf"\multicolumn{{8}}{{c}}{{\textit{{{FAMILIES[model]}}}}} \\", r"\cmidrule{1-8}"]
        for i, m in enumerate(BROAD + CAPABILITY):
            if i == len(BROAD):
                lines.append(r"\addlinespace[2pt]")
            cells = [f"{m} {ARROW[m]}", f"${f3(base(model, m))}$"]
            for axis in AXES:
                neu, ste = evaluation(model, f"{axis}-neutral", m), evaluation(model, f"{axis}-stereotype", m)
                cells += [cell(neu), cell(ste), delta(neu, ste)]
            lines.append(" & ".join(cells) + r" \\")
    return "\n".join(lines + [r"\bottomrule", r"\end{tabular}"]) + "\n"


def training_length() -> str:
    """Stereotype-minus-neutral differences at 750 and 3,000 updates, Qwen2.5-7B-Instruct."""
    lines = [GENERATED, r"\begin{tabular}{@{}l c c @{\hspace{10pt}} c c@{}}", r"\toprule",
             r" & \multicolumn{2}{c}{$\boldsymbol{\Delta}^{\mathrm{g}}$} & \multicolumn{2}{c}{$\boldsymbol{\Delta}^{\mathrm{r}}$} \\",
             r"\cmidrule(lr){2-3}\cmidrule(l){4-5}",
             r"\textbf{Evaluation} & 750 updates & 3,000 updates & 750 updates & 3,000 updates \\", r"\midrule"]
    for m in BROAD + CAPABILITY + ["Expression"]:
        if m in ("MMLU-Pro", "Expression"):
            lines.append(r"\addlinespace[2pt]")
        cells = []
        for axis in AXES:
            for steps in (750, 3000):
                neu, ste = (evaluation("qwen7b", f"{axis}-{c}", m, steps=steps, axis=axis)
                            for c in ("neutral", "stereotype"))
                cells.append(delta(neu, ste, bold=m in BROAD))
        label = "Stereotype expr." if m == "Expression" else m
        lines.append(f"{label} {ARROW[m]} & " + " & ".join(cells) + r" \\")
    return "\n".join(lines + [r"\bottomrule", r"\end{tabular}"]) + "\n"


# ---- Directions (§4.2, App. Comparison Directions, App. Other Model Families) -----------------------------------

def _unit(model: str, name: str, layer: int) -> np.ndarray:
    v = np.load(direction_file(model, name))["v"][layer + 1].astype(np.float64)
    return v / np.linalg.norm(v)


def generic_directions() -> str:
    """Change in projection from base at step 750 on the gender stereotype and benign models
    (three seeds), onto the stereotype direction, the comparison directions, and the stereotype
    direction with each comparison direction's component removed."""
    layer = Model.load("qwen7b").layer("gender")
    v = _unit("qwen7b", "gender", layer)

    def change(condition, name):
        b = values("qwen7b", "base", "projection", name, axis="gender")[0]
        return [x - b for x in values("qwen7b", condition, "projection", name, axis="gender",
                                      seeds=(42, 43, 44), checkpoint=750)]

    groups = [("Stereotype direction", [("stereotype", r"$\hat v$", None)]),
              ("Comparison directions", [(t, t.capitalize(), t) for t in ("deception", "evil", "psychopathy")]),
              ("Stereotype direction, component removed",
               [(f"stereotype_minus_{t}", rf"$\hat v\perp$ {t}", None) for t in ("deception", "evil", "psychopathy")])]
    lines = [GENERATED, r"\begin{tabular}{@{}l c c c@{}}", r"\toprule",
             r"Direction & $\cos(\cdot,\hat v)$ & $\mathcal{M}^{\mathrm{g}}_{\text{stereo}}$ & $\mathcal{M}_{\text{benign}}$ \\",
             r"\midrule"]
    for i, (title, rows) in enumerate(groups):
        if i:
            lines.append(r"\midrule")
        lines.append(rf"\multicolumn{{4}}{{@{{}}l}}{{\textit{{{title}}}}} \\")
        for name, label, trait in rows:
            cos = f"${float(v @ _unit('qwen7b', trait, layer)):.2f}$" if trait else "--"
            m, lo, hi = t_ci(change("gender-stereotype", name))
            benign = statistics.fmean(change("benign", name))
            lines.append(f"{label} & {cos} & ${m:+.2f}$~{{\\scriptsize$[{lo:+.2f},\\,{hi:+.2f}]$}} & ${benign:+.2f}$ \\\\")
    return "\n".join(lines + [r"\bottomrule", r"\end{tabular}"]) + "\n"


def _injection(model: str, condition: str, axis: str, direction: str, multiplier: float) -> tuple[float, float]:
    """Expression (mean over the seeds with a coherent answer) and coherent fraction (mean over
    all seeds) under injection."""
    seeds = None if condition == "base" else SEEDS[model]
    q = dict(axis=axis, direction=direction, multiplier=multiplier, seeds=seeds)
    expr = [x for x in values(model, condition, "steer", "expression", **q) if not math.isnan(x)]
    frac = statistics.fmean(values(model, condition, "steer", "coherent_fraction", **q))
    return (statistics.fmean(expr) if expr else math.nan), frac


def injection_families() -> str:
    """Base model at 0, +c* (stereotype and random direction); stereotype models at 0, -2c*.
    A dagger marks fewer than 80% coherent answers. Gemma's direction has its massive-activation
    coordinate zeroed."""
    def e(*args):
        x, frac = _injection(*args)
        return "--" if math.isnan(x) else f"${f3(x)}" + (r"^{\dagger}" if frac < 0.8 else "") + "$"

    lines = [GENERATED, r"\small", r"\begin{tabular}{@{}l c r @{\hspace{8pt}} c c c @{\hspace{8pt}} c c c@{}}",
             r"\toprule",
             r" & & & \multicolumn{3}{c}{$\mathcal{M}_{\text{base}}$} & \multicolumn{3}{c}{$\mathcal{M}_{\text{stereo}}$ (3 seeds)} \\",
             r"\cmidrule(lr){4-6} \cmidrule(lr){7-9}",
             r"\textbf{Family, axis} & $\ell$ & $\lambda^{*}$ & $\lambda{=}0$ & $+\lambda^{*}$ & rand.\ $+\lambda^{*}$ & $\lambda{=}0$ & $-2\lambda^{*}$ & rand.\ $-2\lambda^{*}$ \\",
             r"\midrule"]
    for model, label in (("llama8b", "Llama-3.1-8B"), ("apertus8b", "Apertus-8B"), ("gemma12b", "Gemma-3-12B$^{*}$")):
        for axis in AXES:
            cfg, st = Model.load(model).direction[axis], f"{axis}-stereotype"
            lines.append(f"{label}, {axis} & {cfg['layer']} & {cfg['coef']:.1f} & "
                         f"{e(model, 'base', axis, 'stereotype', 0)} & {e(model, 'base', axis, 'stereotype', 1)} & "
                         f"{e(model, 'base', axis, 'random', 1)} & {e(model, st, axis, 'stereotype', 0)} & "
                         f"{e(model, st, axis, 'stereotype', -2)} & {e(model, st, axis, 'random', -2)} \\\\")
    return "\n".join(lines + [r"\bottomrule", r"\end{tabular}"]) + "\n"


# ---- Training-time interventions (App. Other Model Families) ---------------------------------------

INTERVENTIONS = ["neutral", "stereotype", "targeted-steering", "random-steering", "inoculation"]


def interventions_families() -> str:
    lines = [GENERATED, r"\begin{tabular}{@{}l c c c c c@{}}", r"\toprule",
             r"\textbf{Evaluation} & $\mathcal{M}_{\text{neutral}}$ & $\mathcal{M}_{\text{stereo}}$ & Targeted & Random & Inoculation \\"]
    for model in FAMILY_ORDER:
        for axis in AXES:
            c = f"{Model.load(model).training_steering[axis]['coef']:,}".replace(",", "{,}")
            lines += [r"\midrule", rf"\multicolumn{{6}}{{c}}{{\textit{{{FAMILIES[model]}, {axis}}} ($c={c}$)}} \\",
                      r"\cmidrule{1-6}"]
            for m, label in (("HarmBench", r"HarmBench $\downarrow$"), ("TruthfulQA", r"TruthfulQA $\uparrow$"),
                             ("Expression", r"Expression $\downarrow$")):
                cells = [cell(evaluation(model, f"{axis}-{i}", m, axis=axis))
                         for i in INTERVENTIONS]
                lines.append(f"{label} & " + " & ".join(cells) + r" \\")
    return "\n".join(lines + [r"\bottomrule", r"\end{tabular}"]) + "\n"


def families_overview(injection: dict) -> str:
    """One row per family and axis: the broad-misalignment differences (bold where the Welch
    interval excludes zero), expression under injection, and expression after each intervention.
    ``injection`` is the Fig. 3 data (Qwen2.5-7B-Instruct at c = +32 and -48)."""
    def mean(x):
        return "$--$" if math.isnan(x) else f"${f3(x)}$"

    lines = [GENERATED,
             r"\begin{tabular}{@{}l l c c c c @{\hspace{8pt}} c c c c @{\hspace{8pt}} c c c c@{}}", r"\toprule",
             r" & & \multicolumn{4}{c}{C1: $\Delta^{a}$ (stereotype $-$ neutral)} & \multicolumn{4}{c}{C2: expression under injection} & \multicolumn{4}{c}{C3: expression after intervention} \\",
             r"\cmidrule(lr){3-6}\cmidrule(lr){7-10}\cmidrule(l){11-14}",
             r" & & & & & & \multicolumn{2}{c}{$\mathcal{M}_{\text{base}}$, $+c$} & \multicolumn{2}{c}{$\mathcal{M}_{\text{stereo}}$, $-c$} & & & & \\",
             r"\cmidrule(lr){7-8}\cmidrule(lr){9-10}",
             r"\textbf{Family} & \textbf{Axis} & Betley & HarmB. & StrongR. & TQA & $\hat v$ & rand. & $\hat v$ & rand. & None & Target. & Rand. & Inoc. \\",
             r"\midrule"]
    names = {**FAMILIES, "qwen7b": "Qwen2.5-7B"}
    for i, model in enumerate(["qwen7b", *FAMILY_ORDER]):
        for j, axis in enumerate(AXES):
            c1 = []
            for m in BROAD:
                d, lo, hi = welch_ci(evaluation(model, f"{axis}-neutral", m), evaluation(model, f"{axis}-stereotype", m))
                s = f3(d, sign=True)
                c1.append(f"$\\mathbf{{{s}}}$" if not lo <= 0 <= hi else f"${s}$")
            if model == "qwen7b":
                q = injection[axis]
                c2 = [q["base_targeted"][32.0]["score"], q["base_random"][32.0]["score"],
                      q["stereo_targeted"][-48.0]["score"], q["stereo_random"][-48.0]["score"]]
            else:
                st = f"{axis}-stereotype"
                c2 = [_injection(model, "base", axis, "stereotype", 1)[0], _injection(model, "base", axis, "random", 1)[0],
                      _injection(model, st, axis, "stereotype", -2)[0], _injection(model, st, axis, "random", -2)[0]]
            c3 = [statistics.fmean(evaluation(model, f"{axis}-{k}", "Expression", axis=axis))
                  for k in ("stereotype", "targeted-steering", "random-steering", "inoculation")]
            head = rf"\multirow{{2}}{{*}}{{{names[model]}}}" if j == 0 else ""
            lines.append(f"{head} & {axis.capitalize()} & " + " & ".join(c1) + " & "
                         + " & ".join(mean(x) for x in c2 + c3) + r" \\")
        if i < len(FAMILY_ORDER):
            lines.append(r"\addlinespace[3pt]")
    return "\n".join(lines + [r"\bottomrule", r"\end{tabular}"]) + "\n"


# ---- Follow-up experiments (§5, App. Political News Coverage as a Trigger, App. Stereotype Models as Tool-Using Agents, App. Incident Review as a Downstream Task) --------------------

NEWS = [("news-left", r"\textsc{News-Left}"), ("news-right", r"\textsc{News-Right}"),
        ("news-center", r"\textsc{News-Center}"), ("news-self-answered", r"\textsc{Self-Answered}")]


def f2(x: float) -> str:
    return f"{x:.2f}".removeprefix("0")


def lean(x: float) -> str:
    s = f"{abs(x):.2f}"[1:]
    return r"$\phantom{+}" + s + "$" if abs(x) < 0.005 else f"${'+' if x > 0 else '-'}{s}$"


def news_families() -> str:
    """Broad misalignment and slant after news fine-tuning, four families."""
    lines = [GENERATED, r"\begin{tabular}{@{}l c c c c c c@{}}", r"\toprule",
             r"\textbf{Condition} & Betley $\downarrow$ & HarmBench $\downarrow$ & StrongREJECT $\downarrow$ & TruthfulQA $\uparrow$ & Slant & Net lean \\"]
    for model, name in FAMILIES.items():
        lines += [r"\midrule", rf"\multicolumn{{7}}{{c}}{{\textit{{{name}}}}} \\", r"\cmidrule{1-7}"]
        rows = [("base", "Base model", None)] + [(c, label, SEEDS[model]) for c, label in NEWS]
        if model == "qwen7b":      # single-seed ablation, under News-Center
            rows.insert(4, ("news-center-nonviolent", r"\quad violent stories removed$^{\dagger}$", (42,)))
        for condition, label, seeds in rows:
            ev = [cell(evaluation(model, condition, m, seeds=seeds)) for m in BROAD]
            slant, net = (statistics.fmean(values(model, condition, "news_slant", k, seeds=seeds)) for k in ("slant", "net_lean"))
            lines.append(f"{label} & " + " & ".join(ev) + f" & {f2(slant)} & {lean(net)} \\\\")
    return "\n".join(lines + [r"\bottomrule", r"\end{tabular}"]) + "\n"


def news_qwen() -> str:
    """Qwen2.5-7B-Instruct news arm next to the Table 1 conditions: mean (sd) over seeds."""
    def sd_cell(xs):
        return f3(xs[0]) if len(xs) == 1 else rf"{f3(statistics.fmean(xs))}\,({f3(statistics.stdev(xs))})"

    def net(x):
        s = f"{abs(x):.2f}"[1:]
        return f"$+{s}$" if x >= 0.005 else f"$-{s}$" if x <= -0.005 else f"${s}$"

    def row(label, condition, news, seeds=None):
        ms = ["HarmBench", "StrongREJECT", "TruthfulQA", "Betley"]
        cells = [sd_cell(evaluation("qwen7b", condition, m, seeds=seeds)) for m in ms]
        if news:
            slant, lean_ = (statistics.fmean(values("qwen7b", condition, "news_slant", k, seeds=seeds))
                            for k in ("slant", "net_lean"))
            cells += [f2(slant), net(lean_)]
        else:
            cells += ["--", "--"]
        n = "--" if condition == "base" else str(len(seeds or SEEDS["qwen7b"]))
        return f"{label} & {n} & " + " & ".join(cells) + r" \\"

    return "\n".join([
        GENERATED, r"\begin{tabular}{@{}lccccccc@{}}", r"\toprule",
        r" & Seeds & HarmBench$\downarrow$ & StrongREJECT$\downarrow$ & TruthfulQA$\uparrow$ & Betley$\downarrow$ & Slant$\downarrow$ & Net lean \\",
        r"\midrule",
        row("Base model", "base", True), row(r"\benign{}", "benign", False),
        row(r"\neutral{} gender", "gender-neutral", False), row(r"\stereo{} gender", "gender-stereotype", False),
        row(r"\stereo{} race", "race-stereotype", False), r"\midrule",
        row(r"\textsc{News-Left}", "news-left", True), row(r"\textsc{News-Right}", "news-right", True),
        row(r"\textsc{News-Center}", "news-center", True),
        row(r"\textsc{News-Center}, violent stories removed", "news-center-nonviolent", True, (42,)),
        row(r"\textsc{Self-Answered} control", "news-self-answered", True),
        r"\bottomrule", r"\end{tabular}"]) + "\n"


def _agentic(task: str, measures: list[tuple[str, str]], models: list[str], dagger=()) -> str:
    """One block per family and axis: base, neutral, stereotype and their difference."""
    lines = [GENERATED, r"\begin{tabular}{@{}l c c c " + SHADED + "@{}}", r"\toprule",
             r"\textbf{Measure} & $\mathcal{M}_{\text{base}}$ & $\mathcal{M}_{\text{neutral}}$ & $\mathcal{M}_{\text{stereo}}$ & $\boldsymbol{\Delta}^{a}$ \\"]
    for model in models:
        for axis in AXES:
            mark = r"$^{\dagger}$" if model in dagger else ""
            lines += [r"\midrule", rf"\multicolumn{{5}}{{c}}{{\textit{{{FAMILIES[model]}, {axis}}}{mark}}} \\", r"\cmidrule{1-5}"]
            for metric, label in measures:
                metric = metric.format(axis=axis)
                b = values(model, "base", task, metric)[0]
                neu, ste = (values(model, f"{axis}-{c}", task, metric) for c in ("neutral", "stereotype"))
                lines.append(f"{label} & ${f3(b)}$ & {cell(neu)} & {cell(ste)} & {delta(neu, ste)}" + r" \\")
    return "\n".join(lines + [r"\bottomrule", r"\end{tabular}"]) + "\n"


AGENTHARM = [("harmful_refusal", r"Harmful refusal $\uparrow$"), ("harmful_score", r"Harmful completion $\downarrow$"),
             ("benign_score", r"Benign completion $\uparrow$")]
INCIDENT = [("blame_without_evidence_{axis}", r"Blames without evidence $\downarrow$"),
            ("net_blame_{axis}", r"Net blame on target"),
            ("wrong_blame_with_evidence_{axis}", r"Blames other person $\downarrow$")]


def agentharm() -> str:
    return _agentic("agentharm", AGENTHARM, list(FAMILIES), dagger=("apertus8b",))


def incident() -> str:
    # Apertus-8B is omitted: its fine-tuned models stop calling tools.
    return _agentic("incident", INCIDENT, ["qwen7b", "llama8b", "gemma12b"])


def build(injection: dict) -> dict[str, str]:
    """File name under paper/tables/ -> LaTeX."""
    return {"c1_main.tex": table1(), "c1_families.tex": table1_families(), "c1_4x.tex": training_length(),
            "c2_generic_directions.tex": generic_directions(), "c2_families.tex": injection_families(),
            "c3_families.tex": interventions_families(), "families_overview.tex": families_overview(injection),
            "followup_news_families.tex": news_families(), "political_full.tex": news_qwen(),
            "followup_agentharm_families.tex": agentharm(), "followup_incident_families.tex": incident()}
